import { Product, Banner, Coupon, Review, Customer } from "./types";

// NOTE: There is no real product photography yet. Each product uses an
// art-directed gradient + label as a placeholder "image" so the storefront
// is fully navigable. Swap `images` for real Cloudinary URLs before launch.

const gradients = [
  "from-stone-900 via-stone-700 to-stone-500",
  "from-accent to-stone-900",
  "from-stone-800 to-stone-950",
  "from-blue-600 via-stone-900 to-black",
  "from-stone-200 to-stone-500",
  "from-black via-stone-800 to-accent",
];

function g(i: number) {
  return gradients[i % gradients.length];
}

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "phantom-oversized-tee",
    name: "Phantom Oversized Tee",
    description:
      "Heavyweight 260gsm cotton, boxy drop-shoulder cut, garment-dyed for a soft worn-in hand feel.",
    category: "oversized",
    tags: ["bestseller", "new"],
    price: 1799,
    compareAtPrice: 2299,
    currency: "INR",
    colors: [
      { name: "Jet Black", hex: "#0A0A0A" },
      { name: "Bone", hex: "#E4E4E4" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    variants: [
      { size: "M", color: "Jet Black", stock: 14, sku: "UF-POT-M-BLK" },
      { size: "L", color: "Jet Black", stock: 8, sku: "UF-POT-L-BLK" },
      { size: "M", color: "Bone", stock: 0, sku: "UF-POT-M-BON" },
    ],
    images: [{ gradient: g(0), label: "Phantom Tee — Front" }, { gradient: g(1), label: "Phantom Tee — Back" }],
    rating: 4.7,
    reviewCount: 132,
    isNew: true,
    isFlashSale: false,
    isBestSeller: true,
    status: "published",
    createdAt: "2026-05-01",
  },
  {
    id: "p2",
    slug: "aftermath-hoodie",
    name: "Aftermath Heavyweight Hoodie",
    description:
      "450gsm brushed fleece, double-lined hood, ribbed cuffs. Built for cold mornings and long silhouettes.",
    category: "hoodies",
    tags: ["bestseller"],
    price: 3299,
    compareAtPrice: 3999,
    currency: "INR",
    colors: [
      { name: "Jet Black", hex: "#0A0A0A" },
      { name: "Slate", hex: "#4A4A4A" },
    ],
    sizes: ["S", "M", "L", "XL"],
    variants: [
      { size: "M", color: "Jet Black", stock: 20, sku: "UF-AH-M-BLK" },
      { size: "L", color: "Slate", stock: 5, sku: "UF-AH-L-SLT" },
    ],
    images: [{ gradient: g(2), label: "Aftermath Hoodie — Front" }],
    rating: 4.9,
    reviewCount: 210,
    isNew: false,
    isFlashSale: true,
    isBestSeller: true,
    status: "published",
    createdAt: "2026-03-14",
  },
  {
    id: "p3",
    slug: "voltage-sneaker",
    name: "Voltage Runner Sneaker",
    description:
      "Knit upper, reactive foam midsole, reflective accent trims. Street-ready and genuinely comfortable.",
    category: "sneakers",
    tags: ["new"],
    price: 5499,
    currency: "INR",
    colors: [
      { name: "Blue Volt", hex: "#3B82F6" },
      { name: "Triple Black", hex: "#0A0A0A" },
    ],
    sizes: ["7", "8", "9", "10", "11"],
    variants: [
      { size: "9", color: "Blue Volt", stock: 6, sku: "UF-VR-9-BLU" },
      { size: "10", color: "Triple Black", stock: 11, sku: "UF-VR-10-BLK" },
    ],
    images: [{ gradient: g(3), label: "Voltage Sneaker" }],
    rating: 4.6,
    reviewCount: 87,
    isNew: true,
    isFlashSale: false,
    isBestSeller: false,
    status: "published",
    createdAt: "2026-06-02",
  },
  {
    id: "p4",
    slug: "essential-crew-tee",
    name: "Essential Crew Tee",
    description: "Everyday 220gsm combed cotton crew neck. The one you'll reach for constantly.",
    category: "t-shirts",
    tags: [],
    price: 999,
    currency: "INR",
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Jet Black", hex: "#0A0A0A" },
    ],
    sizes: ["S", "M", "L", "XL"],
    variants: [
      { size: "M", color: "White", stock: 30, sku: "UF-ECT-M-WHT" },
      { size: "L", color: "Jet Black", stock: 25, sku: "UF-ECT-L-BLK" },
    ],
    images: [{ gradient: g(4), label: "Essential Crew Tee" }],
    rating: 4.4,
    reviewCount: 64,
    isNew: false,
    isFlashSale: false,
    isBestSeller: false,
    status: "published",
    createdAt: "2026-01-20",
  },
  {
    id: "p5",
    slug: "utility-crossbody",
    name: "Utility Crossbody Bag",
    description: "Water-resistant cordura, moulded base, adjustable webbing strap.",
    category: "accessories",
    tags: ["new"],
    price: 1899,
    currency: "INR",
    colors: [{ name: "Jet Black", hex: "#0A0A0A" }],
    sizes: ["One Size"],
    variants: [{ size: "One Size", color: "Jet Black", stock: 40, sku: "UF-UCB-OS-BLK" }],
    images: [{ gradient: g(5), label: "Utility Crossbody Bag" }],
    rating: 4.5,
    reviewCount: 41,
    isNew: true,
    isFlashSale: false,
    isBestSeller: false,
    status: "published",
    createdAt: "2026-06-10",
  },
  {
    id: "p6",
    slug: "momentum-track-pant",
    name: "Momentum Track Pant",
    description: "Tapered fit, brushed interior, zip ankle cuffs. Built to move.",
    category: "men",
    tags: ["bestseller"],
    price: 2399,
    compareAtPrice: 2799,
    currency: "INR",
    colors: [
      { name: "Jet Black", hex: "#0A0A0A" },
      { name: "Slate", hex: "#4A4A4A" },
    ],
    sizes: ["S", "M", "L", "XL"],
    variants: [{ size: "M", color: "Jet Black", stock: 18, sku: "UF-MTP-M-BLK" }],
    images: [{ gradient: g(1), label: "Momentum Track Pant" }],
    rating: 4.6,
    reviewCount: 98,
    isNew: false,
    isFlashSale: false,
    isBestSeller: true,
    status: "published",
    createdAt: "2026-02-11",
  },
  {
    id: "p7",
    slug: "drift-cropped-hoodie",
    name: "Drift Cropped Hoodie",
    description: "Cropped fit fleece hoodie with raw hem finish and oversized kangaroo pocket.",
    category: "women",
    tags: ["new"],
    price: 2699,
    currency: "INR",
    colors: [
      { name: "Bone", hex: "#E4E4E4" },
      { name: "Jet Black", hex: "#0A0A0A" },
    ],
    sizes: ["XS", "S", "M", "L"],
    variants: [{ size: "S", color: "Bone", stock: 12, sku: "UF-DCH-S-BON" }],
    images: [{ gradient: g(0), label: "Drift Cropped Hoodie" }],
    rating: 4.8,
    reviewCount: 56,
    isNew: true,
    isFlashSale: true,
    isBestSeller: false,
    status: "published",
    createdAt: "2026-06-20",
  },
  {
    id: "p8",
    slug: "signal-cap",
    name: "Signal Six-Panel Cap",
    description: "Structured six-panel cap with embroidered wordmark and adjustable strap.",
    category: "accessories",
    tags: [],
    price: 799,
    currency: "INR",
    colors: [{ name: "Jet Black", hex: "#0A0A0A" }],
    sizes: ["One Size"],
    variants: [{ size: "One Size", color: "Jet Black", stock: 50, sku: "UF-SSC-OS-BLK" }],
    images: [{ gradient: g(2), label: "Signal Cap" }],
    rating: 4.3,
    reviewCount: 29,
    isNew: false,
    isFlashSale: false,
    isBestSeller: false,
    status: "published",
    createdAt: "2025-12-05",
  },
];

export const CATEGORIES: { key: Product["category"]; label: string; blurb: string }[] = [
  { key: "men", label: "Men", blurb: "Foundational fits" },
  { key: "women", label: "Women", blurb: "Cropped & tailored" },
  { key: "oversized", label: "Oversized", blurb: "Drop-shoulder staples" },
  { key: "hoodies", label: "Hoodies", blurb: "Heavyweight fleece" },
  { key: "t-shirts", label: "T-Shirts", blurb: "Everyday cotton" },
  { key: "sneakers", label: "Sneakers", blurb: "Street-ready runners" },
  { key: "accessories", label: "Accessories", blurb: "Finish the fit" },
];

export const BANNERS: Banner[] = [
  {
    id: "b1",
    title: "The Aftermath Drop",
    subtitle: "Heavyweight fleece, engineered for winter.",
    ctaLabel: "Shop the drop",
    ctaHref: "/shop?tag=new",
    gradient: "from-black via-stone-900 to-accent",
    active: true,
  },
];

export const COUPONS: Coupon[] = [
  {
    code: "URBAN10",
    type: "percentage",
    value: 10,
    minPurchase: 1500,
    usageLimit: 500,
    usedCount: 128,
    expiresAt: "2026-12-31",
    active: true,
  },
  {
    code: "FLAT200",
    type: "fixed",
    value: 200,
    minPurchase: 2000,
    usageLimit: 300,
    usedCount: 40,
    expiresAt: "2026-09-30",
    active: true,
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    productId: "p1",
    author: "Aarav K.",
    rating: 5,
    comment: "Fit is exactly as pictured, fabric feels genuinely premium.",
    date: "2026-06-01",
    approved: true,
  },
  {
    id: "r2",
    productId: "p2",
    author: "Simran D.",
    rating: 5,
    comment: "Warmest hoodie I own, worth every rupee.",
    date: "2026-05-20",
    approved: true,
  },
  {
    id: "r3",
    productId: "p1",
    author: "Rohan M.",
    rating: 4,
    comment: "Great tee, runs slightly large so size down.",
    date: "2026-06-15",
    approved: true,
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "c1",
    name: "Aarav Kapoor",
    email: "aarav@example.com",
    phone: "+91 90000 00001",
    ordersCount: 4,
    totalSpent: 12400,
    joinedAt: "2025-11-02",
  },
  {
    id: "c2",
    name: "Simran Dey",
    email: "simran@example.com",
    phone: "+91 90000 00002",
    ordersCount: 2,
    totalSpent: 5600,
    joinedAt: "2026-02-18",
  },
];

export const TESTIMONIALS = [
  { author: "Aarav K.", quote: "The fits actually look like the photos. Rare these days.", rating: 5 },
  { author: "Simran D.", quote: "Fast delivery, quality feels premium in hand.", rating: 5 },
  { author: "Rohan M.", quote: "Been wearing the Aftermath hoodie on rotation for weeks.", rating: 4 },
];
